<template>
  <PolygonjsScene
    :sceneName="'scene_01'"
    :loadFunction="loadFunction"
    :autoPlay="true"
    :displayLoadingProgressBar="true"
    :posterExtension="'jpg'"
    baseUrl="."
  />
</template>

<script lang="ts">
import { defineComponent, computed } from "vue";
import { PolygonjsScene } from "@polygonjs/vue3";
import { loadScene_scene_01 } from "../scenes/scene_01/autogenerated/loadScene";

export default defineComponent({
  name: "scene-01",

  components: {
    PolygonjsScene,
  },
  setup() {
    const loadFunction = computed(() => loadScene_scene_01);

    return {
      loadFunction,
    };
  },
});
</script>
